export type DevMapEntry = {
  category: string;
  file: string;
  role: string;
  editable: string[];
  note: string;
};

export const DEV_MAP: DevMapEntry[] = [
  {
    category: "공통 레이아웃 / 메뉴",
    file: "src/app/layout.tsx",
    role: "전체 앱 공통 헤더/메뉴 구조",
    editable: ["상단 메뉴 이름 변경", "메뉴 순서/링크 경로 변경", "헤더 우측 버튼 배치"],
    note: "메인 헤더 구조 변경 시 globals.css의 .app-site-header 관련 스타일도 함께 확인",
  },
  {
    category: "공통 레이아웃 / 메뉴",
    file: "src/app/globals.css",
    role: "전역 스타일(헤더/메뉴/공용 버튼/페이지 톤)",
    editable: ["상단 헤더 정렬(flex)", "메뉴 글자 크기/간격", "전역 버튼 hover 색상", "모바일 네비 그리드"],
    note: "전역 button, .btn 규칙 영향 범위가 넓어서 변경 시 다른 화면도 함께 확인",
  },
  {
    category: "공통 레이아웃 / 메뉴",
    file: "src/app/DevMapButton.tsx",
    role: "헤더 우측 개발 구조 이동 버튼",
    editable: ["톱니 버튼 아이콘/크기", "aria-label 문구", "dev-map 이동 경로"],
    note: "",
  },
  {
    category: "상품 관리",
    file: "src/app/products/ProductsClient.tsx",
    role: "상품 목록 메인 화면(검색/필터/행 렌더/재고조정 트리거)",
    editable: [
      "상품 검색창 동작",
      "카테고리 필터/정렬 UI",
      "수량변경일 표시 셀",
      "하단 액션 버튼 구성",
      "목록 정렬 기준 추가",
    ],
    note: "목록 데이터 반영 방식은 page.tsx 서버 props + local state 병합 구조",
  },
  {
    category: "상품 관리",
    file: "src/app/products/ProductCard.tsx",
    role: "상품 카드 단위 UI(재고/옵션/수량변경일/요약 라인)",
    editable: ["카드 헤더 구성", "수량변경일 아래 요약 문구", "옵션 재고 표시 레이아웃", "카드 내 +1/-1 버튼 영역"],
    note: "",
  },
  {
    category: "상품 관리",
    file: "src/app/products/AddProductModal.tsx",
    role: "상품 신규 등록 모달",
    editable: ["등록 입력 필드", "필수값 검증 문구", "초기값/placeholder", "등록 버튼 흐름"],
    note: "",
  },
  {
    category: "상품 관리",
    file: "src/app/products/EditProductModal.tsx",
    role: "상품 수정 모달",
    editable: ["수정 입력 필드", "저장 버튼 동작", "상품 메모/가격/재고 수정 UI"],
    note: "재고 직접 수정 시 stock_change_summary 초기화 로직은 actions.ts에서 처리",
  },
  {
    category: "상품 관리",
    file: "src/app/products/VariantEditor.tsx",
    role: "옵션(variant) 편집 UI",
    editable: ["옵션 행 추가/삭제", "옵션별 재고 입력칸", "옵션 컬럼(색상/성별/사이즈) 표시"],
    note: "",
  },
  {
    category: "상품 관리",
    file: "src/app/products/csvProductPipeline.ts",
    role: "CSV 업로드 파싱/정규화 파이프라인",
    editable: ["CSV 헤더 매핑", "필드 정규화 규칙", "기본값 처리", "업로드 오류 메시지 기준"],
    note: "CSV 업로드 API(route.ts)와 함께 확인하면 흐름 파악이 쉬움",
  },
  {
    category: "상품 관리",
    file: "src/app/products/actions.ts",
    role: "상품/옵션 저장 액션, 재고 증감, DB 반영 핵심 로직",
    editable: ["상품 저장 트랜잭션", "재고 +1/-1 처리", "수량변경일 기록", "stock_change_summary 반영 방식"],
    note: "재고 관련 핵심 파일. 화면 문제라도 실제 저장값 이상 시 이 파일부터 확인",
  },
  {
    category: "상품 관리",
    file: "src/app/products/stockChangeSummary.ts",
    role: "수량변경 요약 문자열 병합 규칙",
    editable: ["날짜 아래 변경요약 포맷", "같은 초 내 증감 합산 규칙", "라벨별 +/- 병합 기준"],
    note: "",
  },
  {
    category: "사이즈 분석",
    file: "src/features/sizeAnalysis/ui/SizeAnalysisPage.tsx",
    role: "사이즈 분석 화면 전체 UI(업로드~결과/필터/표/뷰 전환)",
    editable: [
      "업로드/시트 선택 단계 UI",
      "결과 요약 카드",
      "상태 필터",
      "클럽별 보기",
      "클럽별 명단",
      "전체 보기 테이블",
      "중복자 표시 방식",
      "범위외 사이즈 표시",
      "검토필요/미분류/수정완료 표시",
    ],
    note: "사이즈 분석 화면 수정의 대부분은 이 파일에서 시작",
  },
  {
    category: "사이즈 분석",
    file: "src/features/sizeAnalysis/uiOutsideAllowedSizes.ts",
    role: "범위외 사이즈 판정(UI 전용) 및 사이즈 확인 우선 규칙",
    editable: ["범위외 판정 기준", "사이즈 확인 표시 우선순위", "범위외 카운트 기준"],
    note: "집계 수량 로직과 분리된 UI 보조 기준",
  },
  {
    category: "사이즈 분석",
    file: "src/features/sizeAnalysis/excludeReasonLabels.ts",
    role: "상태/사유 라벨 표시 문자열 관리",
    editable: ["미분류/검토필요/수정완료 라벨 문구", "제외 사유 표시 명칭", "상태 텍스트 매핑"],
    note: "",
  },
  {
    category: "사이즈 분석",
    file: "src/features/sizeAnalysis/fieldMappingUi.ts",
    role: "분석 전 매핑 단계 UI 유틸",
    editable: ["열 자동매핑 후보 규칙", "매핑 미리보기 보조", "매핑 안내 텍스트"],
    note: "",
  },
  {
    category: "집계 로직",
    file: "src/features/sizeAnalysis/clubSizeAggModes.ts",
    role: "전체/일반/중복/중복제외 수량 및 클럽 집계 핵심",
    editable: [
      "전체 수량 계산 기준",
      "중복 수량 계산 기준",
      "중복 제외 수량 계산 기준",
      "클럽별 성별/사이즈 집계 방식",
      "중복 키 생성 기준",
    ],
    note: "집계 숫자 이상 이슈는 이 파일 우선 확인",
  },
  {
    category: "집계 로직",
    file: "src/features/sizeAnalysis/clubAggMatrixColumns.ts",
    role: "클럽별/상품별 집계 표의 사이즈 열 생성 규칙",
    editable: ["성별/사이즈 열 순서", "열 표시 기준", "사이즈 컬럼 정렬"],
    note: "",
  },
  {
    category: "집계 로직",
    file: "src/features/sizeAnalysis/normalize.ts",
    role: "사이즈 정규화/허용 사이즈 기준",
    editable: ["사이즈 정규화 규칙", "허용 숫자 사이즈 목록", "M/W 표준화 기준"],
    note: "",
  },
  {
    category: "집계 로직",
    file: "src/features/sizeAnalysis/strategies.ts",
    role: "원본 행을 정규화 행으로 변환하는 전략",
    editable: ["구조별 파싱 전략", "sourceRowIndex 생성 기준", "이름/사이즈/수량 추출 방식"],
    note: "",
  },
  {
    category: "엑셀 다운로드",
    file: "src/features/sizeAnalysis/exportSizeAnalysisXlsx.ts",
    role: "사이즈 분석 엑셀 전체 생성(전체목록/클럽별집계/중복자/검토필요)",
    editable: [
      "클럽별 집계 시트 스타일",
      "범위외 사이즈 셀/헤더 색상",
      "클럽별 색상 구분(홀짝)",
      "전체목록 상태/사유 표시",
      "셀 정렬/폰트/컬럼폭",
    ],
    note: "시트별 데이터 분류와 스타일이 같이 있는 파일",
  },
  {
    category: "견적서",
    file: "src/app/transaction-statement/page.tsx",
    role: "견적서/거래명세서 입력 화면 및 다운로드 버튼 진입",
    editable: [
      "견적서 입력 필드",
      "품목 테이블 입력 행",
      "견적서 미리보기 열기",
      "JPG 저장 버튼 동작",
      "공급자 기본 정보값",
    ],
    note: "documentType 토글로 견적서/거래명세서를 같은 페이지에서 처리",
  },
  {
    category: "견적서",
    file: "src/features/transactionStatement/EstimateSheet.tsx",
    role: "견적서 출력/미리보기 렌더 템플릿",
    editable: ["견적서 품목 테이블 레이아웃", "비고 입력란 표시", "공급자 정보 영역", "견적서 상단 수신/행사명 영역"],
    note: "",
  },
  {
    category: "견적서",
    file: "src/features/transactionStatement/exportEstimateExcel.ts",
    role: "견적서 엑셀 생성",
    editable: ["견적서 엑셀 컬럼 구성", "수량/금액 셀 포맷", "견적서 엑셀 시트 구조"],
    note: "",
  },
  {
    category: "거래명세서",
    file: "src/features/transactionStatement/TransactionStatementScreenPanel.tsx",
    role: "거래명세서 입력 화면 하단 거래 요약 패널",
    editable: ["거래 요약 표시", "품목 테이블(화면용)", "공급자/공급받는자 영역", "VAT 토글 패널 UI"],
    note: "",
  },
  {
    category: "거래명세서",
    file: "src/features/transactionStatement/TransactionStatementPrintSheet.tsx",
    role: "거래명세서 미리보기/출력용 템플릿",
    editable: ["미리보기 품목 테이블", "컬럼 폭", "하단 공급자/은행/법적 문구 영역"],
    note: "",
  },
  {
    category: "거래명세서",
    file: "src/app/api/documents/transaction-statement/xlsx/route.ts",
    role: "거래명세서 엑셀 다운로드 API",
    editable: ["거래명세서 엑셀 응답 구조", "서버 검증/에러 메시지", "엑셀 파일 생성 트리거"],
    note: "",
  },
  {
    category: "API / DB",
    file: "src/app/api/size-analysis/run/route.ts",
    role: "사이즈 분석 실행 API",
    editable: ["분석 실행 요청 처리", "실행 오류 응답", "job 실행 흐름"],
    note: "",
  },
  {
    category: "API / DB",
    file: "src/app/api/size-analysis/[jobId]/summary/route.ts",
    role: "사이즈 분석 요약(summary) API",
    editable: ["요약 카드 숫자 응답 필드", "excludedEmptyQtyCount 계산", "상태별 카운트 응답"],
    note: "",
  },
  {
    category: "API / DB",
    file: "src/app/api/size-analysis/[jobId]/rows/route.ts",
    role: "사이즈 분석 행(rows) 조회 API",
    editable: ["상태 필터 rows 응답", "excludedScope=duplicates 처리", "행 정렬 기준"],
    note: "",
  },
  {
    category: "API / DB",
    file: "src/app/api/size-analysis/[jobId]/correct/route.ts",
    role: "사이즈 분석 수동 보정 API",
    editable: ["수량 포함/제외 보정 저장", "보정 사유 저장", "보정 후 응답 형태"],
    note: "",
  },
  {
    category: "API / DB",
    file: "src/app/products/actions.ts",
    role: "상품 저장/재고 반영 서버 액션",
    editable: ["상품 수정 DB 저장", "재고 동기화", "재고 변경일/요약 저장", "moves 로그 저장"],
    note: "",
  },
  {
    category: "API / DB",
    file: "prisma/schema.prisma",
    role: "Prisma DB 스키마 정의",
    editable: ["테이블 컬럼 추가/수정", "모델 관계", "기본값/인덱스"],
    note: "스키마 변경 시 prisma generate/migrate 필요",
  },
  {
    category: "API / DB",
    file: "src/lib/supabaseClient.ts",
    role: "Supabase 클라이언트 생성 공통 유틸",
    editable: ["Supabase 연결 초기화", "환경변수 키 사용 방식", "클라이언트 재사용 구조"],
    note: "",
  },
];

