export type DevMapEntry = {
  category: string;
  file: string;
  role: string;
  editable: string[];
  note: string;
};

export const DEV_MAP: DevMapEntry[] = [
  {
    category: "공통 레이아웃 / 메뉴",
    file: "src/app/layout.tsx",
    role: "상단 메뉴/헤더 구조, 전역 이미지 엑셀 Provider 감싸기",
    editable: [
      "메뉴 이름",
      "메뉴 링크",
      "next/link 클라이언트 이동",
      "메뉴 순서",
      "헤더",
      "개발 구조 버튼",
      "ProductImageExcelDownloadProvider 위치",
    ],
    note: "상단 메뉴·페이지 전환 방식·전역 다운로드 UI 범위가 바뀜",
  },
  {
    category: "공통 레이아웃 / 메뉴",
    file: "src/app/globals.css",
    role: "전역 스타일(메뉴/폰트/색상/정렬)",
    editable: [
      "폰트",
      "색상",
      "정렬",
      "모바일 폰트",
      "버튼 hover",
      "메뉴 스타일",
      "이미지 포함 엑셀 토스트(.product-image-excel-download-toast)",
    ],
    note: "전체 페이지 스타일·다운로드 진행 토스트 위치가 바뀜",
  },
  {
    category: "공통 레이아웃 / 메뉴",
    file: "src/app/ProductImageExcelDownloadProvider.tsx",
    role: "이미지 포함 재고/가격 엑셀 fetch·저장·진행 UI·취소(Abort)",
    editable: ["다운로드 URL", "파일명", "토스트 문구", "취소 동작", "AbortController"],
    note: "다른 메뉴로 이동해도 진행 표시가 유지되도록 layout에서 감쌈",
  },
  {
    category: "공통 레이아웃 / 메뉴",
    file: "src/app/DevMapButton.tsx",
    role: "헤더 우측 톱니 메뉴 버튼",
    editable: ["메뉴 버튼", "톱니 아이콘", "dev-map 이동", "aria-label"],
    note: "",
  },
  {
    category: "상품 관리",
    file: "src/app/products/ProductsClient.tsx",
    role: "상품 목록 메인 화면",
    editable: [
      "상품 카드",
      "정렬",
      "검색",
      "카테고리 필터",
      "수량변경일",
      "다운로드",
      "이미지 포함 재고/가격 엑셀 메뉴(전역 Provider 호출)",
    ],
    note: "상품 목록 화면 UI·이미지 포함 엑셀 진입이 바뀜",
  },
  {
    category: "상품 관리",
    file: "src/app/products/ProductCard.tsx",
    role: "상품 카드 단일 UI",
    editable: ["상품 카드", "수량변경일", "재고 버튼", "색상", "옵션 행"],
    note: "상품 카드 표시가 바뀜",
  },
  {
    category: "상품 관리",
    file: "src/app/products/AddProductModal.tsx",
    role: "상품 등록 모달",
    editable: ["상품 등록", "입력 필드", "비고", "저장 버튼"],
    note: "상품 등록 화면이 바뀜",
  },
  {
    category: "상품 관리",
    file: "src/app/products/EditProductModal.tsx",
    role: "상품 수정 모달",
    editable: ["상품 수정", "가격", "비고", "재고 입력", "저장"],
    note: "상품 수정 화면이 바뀜",
  },
  {
    category: "상품 관리",
    file: "src/app/products/csvProductPipeline.ts",
    role: "CSV 업로드 파이프라인",
    editable: ["CSV 업로드", "컬럼 매핑", "정규화", "업로드 오류", "다운로드 연동"],
    note: "CSV 업로드 결과가 바뀜",
  },
  {
    category: "상품 관리",
    file: "src/app/products/actions.ts",
    role: "상품 저장/재고 변경 서버 액션",
    editable: ["재고 변경", "수량변경일", "상품 저장", "중복 처리", "다운로드 데이터 반영"],
    note: "상품 저장 결과가 바뀜",
  },
  {
    category: "상품 엑셀(이미지)",
    file: "src/app/products/xlsx/productStockExcelJsSheets.ts",
    role: "재고 xlsx ExcelJS 시트(일반+이미지), oneCell+ext 그림",
    editable: ["시트 이름", "이미지 앵커", "열 폭", "헤더", "숫자 서식"],
    note: "이미지 포함 재고 엑셀 레이아웃이 바뀜",
  },
  {
    category: "상품 엑셀(이미지)",
    file: "src/app/products/xlsx/productStockExcelImageFetch.ts",
    role: "엑셀용 이미지 fetch·JPEG 썸네일·행높이·앵커 픽셀 계산",
    editable: ["썸네일 크기", "표시 픽셀", "Supabase URL", "앵커 오프셋"],
    note: "엑셀 안 그림 품질·정렬이 바뀜",
  },
  {
    category: "상품 엑셀(이미지)",
    file: "src/app/products/xlsx/products/with-images/route.ts",
    role: "이미지 포함 재고 xlsx GET",
    editable: ["라우트 경로", "응답 헤더", "번들 로딩"],
    note: "이미지 포함 재고 파일 생성·다운로드가 바뀜",
  },
  {
    category: "상품 엑셀(이미지)",
    file: "src/app/products/xlsx/price-list/with-images/route.ts",
    role: "이미지 포함 가격표 xlsx GET",
    editable: ["가격 컬럼", "이미지 시트", "정렬"],
    note: "이미지 포함 가격 엑셀 결과가 바뀜",
  },
  {
    category: "상품 엑셀(이미지)",
    file: "src/lib/excelXlsxStripInvalidOneCellEditAs.ts",
    role: "xlsx ZIP 후처리로 drawing oneCell 잘못된 editAs 제거(Excel 복구 방지)",
    editable: ["정규식", "대상 경로 xl/drawings"],
    note: "엑셀에서 그림 파트 복구 경고가 나올 때 이 파일부터 확인",
  },
  {
    category: "상품 관리",
    file: "src/app/products/stockChangeSummary.ts",
    role: "수량변경일 요약 문구",
    editable: ["수량변경일", "변경 요약", "재고 +1 -1 문구"],
    note: "수량변경일 표시 문구가 바뀜",
  },
  {
    category: "사이즈 분석",
    file: "src/features/sizeAnalysis/ui/SizeAnalysisPage.tsx",
    role: "사이즈 분석 메인 화면",
    editable: [
      "결과 요약",
      "상태 필터",
      "클럽별",
      "전체 보기",
      "중복",
      "미분류",
      "검토필요",
      "수정완료",
      "범위외 사이즈",
      "색상",
    ],
    note: "사이즈 분석 결과 화면 UI가 바뀜",
  },
  {
    category: "사이즈 분석",
    file: "src/features/sizeAnalysis/uiOutsideAllowedSizes.ts",
    role: "범위외 사이즈 표시 기준",
    editable: ["범위외 사이즈", "사이즈 확인", "허용 사이즈", "색상 대상"],
    note: "범위외 사이즈 표시 대상이 바뀜",
  },
  {
    category: "사이즈 분석",
    file: "src/features/sizeAnalysis/excludeReasonLabels.ts",
    role: "상태/사유 문구",
    editable: ["미분류", "검토필요", "수정완료", "중복 사유", "상태 필터 문구"],
    note: "사이즈 분석 상태 문구가 바뀜",
  },
  {
    category: "집계 로직",
    file: "src/features/sizeAnalysis/clubSizeAggModes.ts",
    role: "집계/중복 계산 핵심",
    editable: ["중복 수량", "중복 제외", "중복", "전체 수량", "일반 수량", "클럽별 집계", "성별/사이즈 집계"],
    note: "중복 수량 계산 결과가 바뀜",
  },
  {
    category: "집계 로직",
    file: "src/features/sizeAnalysis/clubAggMatrixColumns.ts",
    role: "클럽별 집계 컬럼 구성",
    editable: ["클럽별", "정렬", "사이즈 열", "셀 크기"],
    note: "클럽별 집계 표 컬럼이 바뀜",
  },
  {
    category: "집계 로직",
    file: "src/features/sizeAnalysis/normalize.ts",
    role: "사이즈 정규화 기준",
    editable: ["범위외 사이즈 기준", "허용 사이즈", "정규화"],
    note: "사이즈 분류 결과가 바뀜",
  },
  {
    category: "엑셀 다운로드",
    file: "src/features/sizeAnalysis/exportSizeAnalysisXlsx.ts",
    role: "사이즈 분석 엑셀 시트 생성",
    editable: [
      "엑셀",
      "다운로드",
      "클럽별 보기",
      "클럽별 색상",
      "범위외 사이즈 색상",
      "중복 색상",
      "중복 수량",
      "중복 제외",
      "상품목록 시트",
      "폰트",
      "셀 크기",
      "정렬",
    ],
    note: "엑셀 다운로드 결과가 바뀜",
  },
  {
    category: "견적서 / 거래명세서",
    file: "src/app/transaction-statement/page.tsx",
    role: "견적서/거래명세서 입력 화면",
    editable: ["견적서", "거래명세서", "품목 테이블", "비고", "다운로드", "JPG 저장"],
    note: "입력 화면 UI가 바뀜",
  },
  {
    category: "견적서 / 거래명세서",
    file: "src/features/transactionStatement/EstimateSheet.tsx",
    role: "견적서 출력 템플릿",
    editable: ["견적서", "품목 테이블", "비고", "공급자 정보", "폰트", "정렬"],
    note: "견적서 출력 결과가 바뀜",
  },
  {
    category: "견적서 / 거래명세서",
    file: "src/features/transactionStatement/exportEstimateExcel.ts",
    role: "견적서 ExcelJS 생성·도장 이미지·drawing OOXML 보정 호출",
    editable: ["도장 위치", "엑셀 레이아웃", "stripInvalidOneCell"],
    note: "견적서 엑셀에 도장이 있을 때 Excel 복구 경고와 연관",
  },
  {
    category: "견적서 / 거래명세서",
    file: "src/features/transactionStatement/TransactionStatementPrintSheet.tsx",
    role: "거래명세서 출력 템플릿",
    editable: ["거래명세서", "품목 테이블", "컬럼 폭", "공급자 영역", "폰트", "정렬"],
    note: "거래명세서 출력 결과가 바뀜",
  },
  {
    category: "견적서 / 거래명세서",
    file: "src/app/api/documents/transaction-statement/xlsx/route.ts",
    role: "거래명세서 엑셀 API",
    editable: ["거래명세서", "엑셀", "다운로드", "정렬", "컬럼 폭"],
    note: "거래명세서 엑셀 다운로드 결과가 바뀜",
  },
  {
    category: "API / DB",
    file: "src/app/api/size-analysis/run/route.ts",
    role: "size-analysis 실행 API",
    editable: ["size-analysis API", "분석 실행", "오류 응답"],
    note: "사이즈 분석 실행 결과가 바뀜",
  },
  {
    category: "API / DB",
    file: "src/app/api/size-analysis/[jobId]/summary/route.ts",
    role: "size-analysis summary API",
    editable: ["summary API", "결과 요약", "검토필요", "미분류", "수정완료", "범위외 사이즈"],
    note: "요약 숫자 결과가 바뀜",
  },
  {
    category: "API / DB",
    file: "src/app/api/size-analysis/[jobId]/rows/route.ts",
    role: "size-analysis rows API",
    editable: ["상태 필터", "중복", "중복 제외", "정렬", "rows API"],
    note: "행 목록 결과가 바뀜",
  },
  {
    category: "API / DB",
    file: "src/app/products/actions.ts",
    role: "products actions 서버 저장",
    editable: ["products actions", "재고 변경", "수량변경일", "중복 처리"],
    note: "상품 저장/재고 결과가 바뀜",
  },
  {
    category: "API / DB",
    file: "prisma/schema.prisma",
    role: "Prisma schema",
    editable: ["Prisma schema", "DB 컬럼", "모델 관계", "인덱스"],
    note: "DB 스키마가 바뀜",
  },
  {
    category: "API / DB",
    file: "src/lib/supabaseClient.ts",
    role: "Supabase 공통 연결",
    editable: ["Supabase", "연결 설정", "환경변수"],
    note: "Supabase 연결 동작이 바뀜",
  },
];

